### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by fmayam** [navaneethkm004/distube-music-bot#4]
i'm a noob and is this suppossed to happen?

i tried to run it and it stucked at
[DisTube] Downloaded youtube-dl 2021.03.02

**Comment by fmayam** [comment]
after trying for a few hours, it finally logged in, but when i want to play a song and error occurs

(node:3742) UnhandledPromiseRejectionWarning: TypeError [EMOJI_TYPE]: Emoji must be a string or GuildEmoji/ReactionEmoji
    at Message.react (/home/runner/distube-music-bot/node_modules/discord.js/src/structures/Message.js:546:23)
    at Client.<anonymous> (/home/runner/distube-music-bot/index.js:120:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by navaneethkm004** [comment]
did you install it with `node.js` environment. You will get option to select that in the beginning.

**Comment by navaneethkm004** [comment]
If you already did that, try doing `npm ci` or `npm i`. Then restart the bot.

**Comment by fmayam** [comment]
its fixed! thanks, and also thank you for coding this bot!

**Comment by fmayam** [comment]
but now i have another problem if i'm use the command stop

TypeError: Cannot read property 'delete' of undefined
    at Client.<anonymous> (/home/runner/distube-music-bot/index.js:427:173)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
